### ISSUE TITLE
How to solve the HTML inline <script> tag does not support tips? I like atom. I need this function！

### ISSUE THREAD

**Issue by zhangsiyi** [atom/ide-typescript#65] opened 2017-11-23 03:18 UTC
A few things to know before you create an issue

* This package requires [Atom 1.21](https://atom.io)
* We launch a "language server" process on your machine that understands the language you are editing
* What that server can do - syntax compatibility, whether it supports formatting or outlines etc - is outside of our control
* You can see what the language server supports by checking out our README and following the link after "powered by"
* "disconnected", "JSONRPC" or "Content-Header" errors indicate that server process died. We're working on better recovery right now

If you have understood all this, please remove this text and start writing your issue :)

**Comment by 50Wliu** [comment] 2017-11-23 09:47
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #11. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2017-11-23 09:47 UTC
