### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by sangdth** [atom/ide-typescript#51] opened 2017-10-12 10:09 UTC
[Enter steps to reproduce:]

1. Open .js file and edit.
2. Go grab a cup of coffee.

**Atom**: 1.22.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.6.2

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/sangdth/.atom/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:606

Error: Connection is closed.
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:131:28)
    at throwIfClosedOrDisposed (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:606:19)
    at Object.sendNotification (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:660:13)
    at LanguageClientConnection._sendNotification (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:244:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:145:10)
    at ServerManager.projectFilesChanged (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:262:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/project.js:341:40
    at PathWatcher.onNativeEvents (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom Beta.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

### Commands

```
     -5:41.5.0 core:close (input.hidden-input)
     -2:51.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:22.2.0 window:toggle-dev-tools (a.stack-toggle)
     -0:01.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-html-templates 0.1.3 
atom-ide-ui 0.5.0 
atom-jade 0.3.0 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.5 
autoclose-html 0.23.0 
busy-signal 1.4.3 
editorconfig 2.2.2 
emmet 2.4.3 
etheratom 3.1.0 
file-icons 2.1.13 
git-plus 7.10.0 
ide-typescript 0.6.2 
ide-vue 0.1.7 
intentions 1.1.5 
language-babel 2.75.1 
language-ethereum 0.3.9 
language-nunjucks 4.1.0 
language-vue 0.23.1 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
neutron-dark-ui 2.1.4 
nuclide 0.259.0 
prettier-atom 0.40.0 
pure-syntax 0.3.0 
sync-settings 0.8.3 
unity-shader-files 0.3.1 
```

**Comment by rsese** [comment] 2017-10-12 18:49
Thanks for the report!  This is a duplicate of https://github.com/atom/ide-typescript/issues/17, so you can subscribe there if you'd like.  If you can share the debugging details Damien asks for in https://github.com/atom/ide-typescript/issues/17#issuecomment-331324401, that could be helpful too.

**Closed by rsese** 2017-10-12 18:49 UTC
