### ISSUE TITLE
ESLint is TypeScript biased--not recognizing respecting config file for ReactJS

### ISSUE THREAD

**Issue by che-wf** [atom/ide-typescript#40] opened 2017-09-18 22:40 UTC
The description is misleading by suggesting "JavaScript and TypeScript". ESLint doesn't accurately recognize that the code is using `jsx` and not `ts`. I'm getting error specific to TypeScript that do not pertain to ReactJS. It would be better if the description specified only TypeScript or Diagnostics recognized `jsx` language and only called errors for React styles.

**Comment by Arcanemagus** [comment] 2017-09-18 22:46
I think you mean the TypeScript compiler. ESLint has nothing to do with this package.

You can find a similar issue to what you are seeing in https://github.com/atom/ide-typescript/issues/19 related to `flow` style type definitions. This package _only_ supports the base, standard, Javascript. Meaning _no_ extensions on top of it.

**Comment by damieng** [comment] 2017-09-18 22:55
Can you provide actual screenshots, repro steps and exact error messages?

**Comment by jbcoder** [comment] 2017-09-18 22:56
Ah! I see what you're saying. Yes, I'm getting `ts` errors in my plain JS file. I was also seeing ESLint errors when I had the plugin enabled that I wasn't getting from my other ESLinting package. But that's another issue. See example in attached image.
![image](https://user-images.githubusercontent.com/1719239/30568410-ea07ef00-9c89-11e7-8728-e0803534b1bd.png)

**Comment by damieng** [comment] 2017-09-25 17:22
I think what you're actually seeing there is that the version of typescript doesn't support import etc. yet.

**Comment by nemo** [comment] 2017-09-28 22:57
Ditto ^. I'm getting a *lot* of errors on `jsx` files (which I guess has nothing to do with them being jsx) for `import`s and class decorators.

**Comment by chee** [comment] 2017-10-04 18:41
i'm running into this with code using the [stage 3 class fields proposal](https://github.com/tc39/proposal-class-fields) and code using [stage 3 dynamic import](https://github.com/tc39/proposal-dynamic-import).

dynamic import seems to exist in typescript now, https://github.com/Microsoft/TypeScript/pull/16281

and i was sure class fields / member properties already did

**Comment by chee** [comment] 2017-10-04 18:42
oh the class fields thing was a false alarm caused by a dynamic import confusing and frightening typescript further up the file

**Comment by damieng** [comment] 2017-10-04 20:08
@chee those features are in TypeScript 2.5 - we're currently locked to 2.4 as that's what the underlying language server does.  It's being tracked at https://github.com/sourcegraph/javascript-typescript-langserver/pull/359

**Comment by jbcoder** [comment] 2017-10-04 22:36
@chee "bizarrely combative"? Not really. Assuming and misguided? Quite possibly. 

Do you suggest a better title?

**Comment by damieng** [comment] 2018-11-29 20:53
Should be fixed with the new ide-typescript 0.8.0 update.

**Closed by damieng** 2018-11-29 20:53 UTC
