### ISSUE TITLE
Type aliases in Javascript for Flow typed

### ISSUE THREAD

**Issue by verydanny** [atom/ide-typescript#28] opened 2017-09-13 14:43 UTC
Currently get error "'type aliases' can only be used in a .ts file.", but my JS file is flow-typed so I am able to use Types. Thanks!

**Comment by damieng** [comment] 2017-09-13 15:22
Yes, ide-typescript does not support flow.  I would recommend you try the ide-flow package.  If you want both installed you can turn off the JavaScript support for ide-typescript in the package settings.

Duplicate of #19

**Closed by damieng** 2017-09-13 15:22 UTC
