### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by ivanross** [atom/ide-typescript#74] opened 2017-12-26 14:24 UTC
**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.3
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.2

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/ivanross/.atom/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:365:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:167:10)
    at ServerManager.projectFilesChanged (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:248:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at didChangeCallback (/Applications/Atom.app/Contents/Resources/app/src/project.js:350:28)
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

### Commands

```
     -7:26.6.0 core:copy (input.hidden-input)
     -4:37.5.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-electron-snippets 2.0.3 
atom-ide-ui 0.7.0 
atom-typescript 11.0.10 
autocomplete-paths 2.12.1 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.14 
git-diff-details 1.4.0 
highlight-selected 0.13.1 
ide-typescript 0.7.2 
intentions 1.1.5 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
nucleus-dark-ui 0.12.3 
nuclide 0.273.0 
open-in-browser 0.5.2 
pigments 0.40.2 
pristine-ui 1.1.11 
regex-railroad-diagram 0.19.4 
toggler 0.3.1 
tree-view-git-status 1.4.0 
```

**Comment by liuderchi** [comment] 2017-12-26 16:04
this looks similar to #17

**Comment by rsese** [comment] 2017-12-27 05:39
Thanks @liuderchi :v:  Closing as a duplicate of #17 but if you have any more details about reproducing the error @ivanross, please let us know in #17.

**Closed by rsese** 2017-12-27 05:39 UTC
