### ISSUE TITLE
Uncaught Error: Connection is closed.

### ISSUE THREAD

**Issue by shkurata** [atom/ide-typescript#67] opened 2017-12-04 12:01 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [ide-typescript](https://github.com/atom/ide-typescript) package 0.7.0

### Stack Trace

Uncaught Error: Connection is closed.

```
At /Users/nikolayneykov/.atom/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:613

Error: Connection is closed.
    at /packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendNotification (/packages/ide-typescript/node_modules/vscode-jsonrpc/lib/main.js:667:13)
    at LanguageClientConnection._sendNotification (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:242:15)
    at LanguageClientConnection.didChangeWatchedFiles (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/languageclient.js:143:10)
    at ServerManager.projectFilesChanged (/packages/ide-typescript/node_modules/atom-languageclient/build/lib/server-manager.js:233:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/project.js:341:40
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:671:15)
    at /Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:567:31
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:448:26)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:177:15)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
angularjs 0.5.1 
atom-beautify 0.30.9 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.6 
atom-typescript 11.0.10 
busy-signal 1.4.3 
emmet 2.4.3 
emmet-jsx-props 1.2.5 
file-icons 2.1.14 
git-plus 7.10.0 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
ide-typescript 0.7.0 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-eslint 8.4.0 
linter-scss-lint 3.1.1 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
open-in-browsers 0.0.30 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
react-snippets 1.0.1 
sass-autocompile 0.13.3 
time-status 1.1.2 
typescript-modules-helper 0.8.0 
vim-mode-plus 1.22.0 
```

**Comment by rsese** [comment] 2017-12-05 06:00
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/ide-typescript/issues/17 so you can  subscribe there for updates if you'd like.  If you have any more details about reproducing this error, please let us know in the issue!

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-05 06:00 UTC
