### ISSUE TITLE
Hyperclick jumps to non-existent file

### ISSUE THREAD

**Issue by C-Bouthoorn** [atom/ide-typescript#121] opened 2018-08-11 21:30 UTC
How to reproduce:

First start a clean run of Atom:
```bash
cd $(mktemp -d)
export ATOM_HOME=$(pwd)/atom
export HOME=$(pwd)
atom
```

Go to the package installer and install `atom-ide-ui` (0.13.0) and `ide-typescript` (0.7.6).

Create a new typescript file (`index.ts`) and write the following:

```typescript
"Hello World".toUpperCase()
```

Now hold <kbd>Ctrl</kbd> and click with the LMB on `toUpperCase` (active Hyperclick)

A new tab opens, with the title of `lib.d.ts -- TypeScript?v2.8.3#lib -- git:/github.com/Microsoft/TypeScript?v2.8.3#lib`  (Note `git:/github.com` with the single forward slash), but no code appears.

In case it matters:
```bash
$ atom --version
Atom    : 1.29.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ apm --version
apm  1.19.0
npm  6.3.0
node 10.8.0 x64
atom 1.29.0
python 2.7.15
git 2.18.0

$ uname -r
4.17.12-arch1-1-ARCH
```

**Comment by damieng** [comment] 2018-11-29 20:44
Duplicate of #10

**Closed** 2018-11-29 20:46 UTC
